export const cartTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  INCREASE_ITEM_TO_CART: 'INCREASE_ITEM_TO_CART',
  DECREASE_ITEM_TO_CART: 'DECREASE_ITEM_TO_CART',
  REMOVE_ITEM_TO_CART: 'REMOVE_ITEM_TO_CART',
};
